"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const validations_1 = require("../validations");
const index_1 = require("../controllers/index");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const router = (0, express_1.Router)();
router.get("/", index_1.getUsers);
router.get("/email/:email", index_1.getUserByEmail);
router.get("/:id", auth_middleware_1.authMiddleware, index_1.getUserById);
router.post("/", validations_1.createUserValidation, index_1.createUser);
router.patch("/:id", auth_middleware_1.authMiddleware, validations_1.updateUserValidation, index_1.updateUser);
router.delete("/:id", auth_middleware_1.authMiddleware, validations_1.deleteUserValidation, index_1.deleteUser);
router.patch("/logical-delete/:id", auth_middleware_1.authMiddleware, index_1.logicalDeleteUser);
exports.default = router;
